name: CI - Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Python ${{ matrix.python-version }} on ${{ runner.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Show Python version
        run: |
          python -V
          which python

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          # Minimal deps required to run tests and spawn the MCP server via FastMCP Client
          pip install fastmcp pytest pytest-asyncio pytest-timeout

      - name: Run tests
        env:
          # No provider keys required; tests are hermetic
          PYTHONUNBUFFERED: "1"
        run: |
          pytest -q

